# Generated by Django 4.2.27 on 2026-01-10 22:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('VEHICULAR', 'Vehicular Accident'), ('MOTORCYCLE', 'Motorcycle Accident'), ('PEDESTRIAN', 'Pedestrian Incident'), ('OBSTACLE', 'Road Obstacle'), ('POTHOLE', 'Deep Pothole'), ('BROKEN_VEHICLE', 'Broken Down Vehicle')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('RESOLVED', 'Resolved/Fixed'), ('FALSE', 'False Report')], default='PENDING', max_length=20)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HazardMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='hazard_media/%Y/%m/%d/')),
                ('is_video', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='hazards.hazard')),
            ],
        ),
    ]
